[package]
name = "ffdb-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
base64.workspace = true
ffdb-protocol = { path = "../protocol" }
ipnet.workspace = true
secrecy.workspace = true
thiserror.workspace = true
url.workspace = true
uuid.workspace = true

[lints]
workspace = true
