DROP TABLE IF EXISTS idempotency_keys;
DROP TABLE IF EXISTS backups;
DROP TRIGGER IF EXISTS audit_events_no_update_or_delete ON audit_events;
DROP FUNCTION IF EXISTS ffdb_deny_audit_mutation();
DROP TABLE IF EXISTS audit_events;
DROP TABLE IF EXISTS rate_limit_state;
DROP TABLE IF EXISTS usage_buckets;
DROP TABLE IF EXISTS project_migrations;
DROP TABLE IF EXISTS email_jobs;
DROP TABLE IF EXISTS email_templates;
DROP TABLE IF EXISTS provider_settings;
DROP TABLE IF EXISTS auth_one_time_tokens;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS refresh_token_families;
DROP TABLE IF EXISTS auth_sessions;
DROP TABLE IF EXISTS auth_users;
DROP TABLE IF EXISTS jwt_signing_keys;
DROP TABLE IF EXISTS api_keys;
DROP TABLE IF EXISTS worker_leases;
ALTER TABLE project_databases DROP CONSTRAINT IF EXISTS project_databases_route_fk;
DROP TABLE IF EXISTS database_routes;
ALTER TABLE projects DROP CONSTRAINT IF EXISTS projects_database_fk;
DROP TABLE IF EXISTS project_databases;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS nodes;
DROP TABLE IF EXISTS organization_memberships;
DROP TABLE IF EXISTS organizations;
DROP TABLE IF EXISTS platform_sessions;
DROP TABLE IF EXISTS platform_users;
