-- FFDB control-plane schema. UUIDs are generated by the service so the schema
-- has no extension dependency. Security-sensitive tokens are represented only
-- by a non-secret lookup prefix and a keyed digest.

CREATE TABLE platform_users (
    id uuid PRIMARY KEY,
    email text NOT NULL,
    password_phc text NOT NULL,
    email_verified_at timestamptz,
    disabled_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX platform_users_email_unique ON platform_users(lower(email));

CREATE TABLE platform_sessions (
    id uuid PRIMARY KEY,
    family_id uuid NOT NULL,
    user_id uuid NOT NULL REFERENCES platform_users(id) ON DELETE RESTRICT,
    lookup_prefix text NOT NULL UNIQUE,
    keyed_hash bytea NOT NULL CHECK (octet_length(keyed_hash) = 32),
    issued_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    used_at timestamptz,
    replaced_by uuid UNIQUE,
    revoked_at timestamptz,
    revoke_reason text,
    CONSTRAINT platform_sessions_replacement_fk FOREIGN KEY (replaced_by)
        REFERENCES platform_sessions(id) DEFERRABLE INITIALLY DEFERRED,
    CHECK (expires_at > issued_at),
    CHECK ((used_at IS NULL) = (replaced_by IS NULL))
);
CREATE INDEX platform_sessions_family_idx ON platform_sessions(family_id);
CREATE INDEX platform_sessions_user_active_idx
    ON platform_sessions(user_id) WHERE revoked_at IS NULL;

CREATE TABLE organizations (
    id uuid PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    display_name text NOT NULL,
    disabled_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (slug ~ '^[a-z0-9][a-z0-9-]{1,62}$')
);

CREATE TABLE organization_memberships (
    organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    user_id uuid NOT NULL REFERENCES platform_users(id) ON DELETE RESTRICT,
    role text NOT NULL CHECK (role IN ('owner', 'admin', 'developer', 'viewer')),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (organization_id, user_id)
);

CREATE TABLE nodes (
    id uuid PRIMARY KEY,
    name text NOT NULL UNIQUE,
    lifecycle_state text NOT NULL DEFAULT 'active'
        CHECK (lifecycle_state IN ('active', 'draining', 'disabled')),
    fencing_generation bigint NOT NULL DEFAULT 1 CHECK (fencing_generation > 0),
    last_heartbeat_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- projects.database_id and project_databases.project_id form a deferred cycle.
-- PostgreSQL therefore refuses to commit a project without exactly one database,
-- while UNIQUE(project_id) refuses a second database for the same project.
CREATE TABLE projects (
    id uuid PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    database_id uuid NOT NULL UNIQUE,
    slug text NOT NULL,
    display_name text NOT NULL,
    region text NOT NULL DEFAULT 'local',
    lifecycle_state text NOT NULL DEFAULT 'provisioning'
        CHECK (lifecycle_state IN ('provisioning', 'active', 'suspended', 'restoring', 'deleting', 'deleted', 'failed')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (organization_id, slug),
    UNIQUE (id, database_id),
    CHECK (slug ~ '^[a-z0-9][a-z0-9-]{1,62}$')
);

CREATE TABLE project_databases (
    id uuid PRIMARY KEY,
    project_id uuid NOT NULL UNIQUE,
    route_id uuid NOT NULL UNIQUE,
    schema_version bigint NOT NULL DEFAULT 0 CHECK (schema_version >= 0),
    lifecycle_state text NOT NULL DEFAULT 'provisioning'
        CHECK (lifecycle_state IN ('provisioning', 'active', 'migrating', 'restoring', 'failed')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, id),
    UNIQUE (id, route_id),
    CONSTRAINT project_databases_project_fk
        FOREIGN KEY (project_id) REFERENCES projects(id)
        ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED
);

ALTER TABLE projects ADD CONSTRAINT projects_database_fk
    FOREIGN KEY (id, database_id) REFERENCES project_databases(project_id, id)
    ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE database_routes (
    id uuid PRIMARY KEY,
    project_id uuid NOT NULL,
    database_id uuid NOT NULL UNIQUE,
    node_id uuid NOT NULL REFERENCES nodes(id) ON DELETE RESTRICT,
    generation bigint NOT NULL CHECK (generation > 0),
    assigned_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (database_id, id),
    CONSTRAINT database_routes_database_fk
        FOREIGN KEY (project_id, database_id)
        REFERENCES project_databases(project_id, id)
        ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED
);

ALTER TABLE project_databases ADD CONSTRAINT project_databases_route_fk
    FOREIGN KEY (id, route_id) REFERENCES database_routes(database_id, id)
    ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE worker_leases (
    database_id uuid PRIMARY KEY REFERENCES project_databases(id) ON DELETE RESTRICT,
    node_id uuid NOT NULL REFERENCES nodes(id) ON DELETE RESTRICT,
    generation bigint NOT NULL CHECK (generation > 0),
    lease_id uuid NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    renewed_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE api_keys (
    id uuid PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    project_id uuid REFERENCES projects(id) ON DELETE RESTRICT,
    name text NOT NULL,
    lookup_prefix text NOT NULL UNIQUE,
    keyed_hash bytea NOT NULL CHECK (octet_length(keyed_hash) = 32),
    scopes text[] NOT NULL,
    created_by uuid NOT NULL,
    expires_at timestamptz,
    last_used_at timestamptz,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (lookup_prefix ~ '^[A-Za-z0-9_-]{12,32}$'),
    CHECK (cardinality(scopes) > 0)
);
CREATE INDEX api_keys_project_idx ON api_keys(project_id) WHERE revoked_at IS NULL;

CREATE TABLE jwt_signing_keys (
    id uuid PRIMARY KEY,
    project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
    kid text NOT NULL,
    public_key bytea NOT NULL CHECK (octet_length(public_key) = 32),
    encrypted_private_key bytea,
    encryption_key_version integer,
    status text NOT NULL CHECK (status IN ('pending', 'active', 'grace', 'revoked')),
    valid_from timestamptz NOT NULL,
    valid_until timestamptz,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, kid),
    CHECK ((encrypted_private_key IS NULL) = (encryption_key_version IS NULL)),
    CHECK (valid_until IS NULL OR valid_until > valid_from)
);
CREATE UNIQUE INDEX jwt_one_active_key_per_project
    ON jwt_signing_keys(project_id) WHERE status = 'active';

CREATE TABLE auth_users (
    id uuid PRIMARY KEY,
    project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
    email text NOT NULL,
    password_phc text NOT NULL,
    role text NOT NULL DEFAULT 'authenticated',
    custom_claims jsonb NOT NULL DEFAULT '{}'::jsonb,
    email_verified_at timestamptz,
    disabled_at timestamptz,
    password_changed_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, id)
);
CREATE UNIQUE INDEX auth_users_project_email_unique
    ON auth_users(project_id, lower(email));

CREATE TABLE auth_sessions (
    id uuid PRIMARY KEY,
    project_id uuid NOT NULL,
    user_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    revoke_reason text,
    CONSTRAINT auth_sessions_user_fk FOREIGN KEY (project_id, user_id)
        REFERENCES auth_users(project_id, id) ON DELETE RESTRICT
);
CREATE INDEX auth_sessions_user_active_idx
    ON auth_sessions(project_id, user_id) WHERE revoked_at IS NULL;

CREATE TABLE refresh_token_families (
    id uuid PRIMARY KEY,
    project_id uuid NOT NULL,
    user_id uuid NOT NULL,
    session_id uuid NOT NULL UNIQUE REFERENCES auth_sessions(id) ON DELETE RESTRICT,
    revoked_at timestamptz,
    revoke_reason text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT refresh_families_user_fk FOREIGN KEY (project_id, user_id)
        REFERENCES auth_users(project_id, id) ON DELETE RESTRICT
);

CREATE TABLE refresh_tokens (
    id uuid PRIMARY KEY,
    family_id uuid NOT NULL REFERENCES refresh_token_families(id) ON DELETE RESTRICT,
    lookup_prefix text NOT NULL UNIQUE,
    keyed_hash bytea NOT NULL CHECK (octet_length(keyed_hash) = 32),
    issued_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    used_at timestamptz,
    replaced_by uuid UNIQUE,
    CONSTRAINT refresh_tokens_replacement_fk FOREIGN KEY (replaced_by)
        REFERENCES refresh_tokens(id) DEFERRABLE INITIALLY DEFERRED,
    CHECK (expires_at > issued_at),
    CHECK ((used_at IS NULL) = (replaced_by IS NULL))
);
CREATE INDEX refresh_tokens_family_idx ON refresh_tokens(family_id);

CREATE TABLE auth_one_time_tokens (
    id uuid PRIMARY KEY,
    project_id uuid NOT NULL,
    user_id uuid NOT NULL,
    purpose text NOT NULL CHECK (purpose IN ('email_verification', 'password_reset')),
    lookup_prefix text NOT NULL UNIQUE,
    keyed_hash bytea NOT NULL CHECK (octet_length(keyed_hash) = 32),
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT one_time_tokens_user_fk FOREIGN KEY (project_id, user_id)
        REFERENCES auth_users(project_id, id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX one_time_tokens_user_active_idx
    ON auth_one_time_tokens(project_id, user_id, purpose) WHERE consumed_at IS NULL;

CREATE TABLE provider_settings (
    id uuid PRIMARY KEY,
    project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
    provider_kind text NOT NULL,
    endpoint_url text,
    encrypted_settings bytea NOT NULL,
    encryption_key_version integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, provider_kind)
);

CREATE TABLE email_templates (
    id uuid PRIMARY KEY,
    project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
    name text NOT NULL CHECK (name IN ('verification', 'password_reset', 'email_change', 'invitation', 'magic_link')),
    version integer NOT NULL CHECK (version > 0),
    subject_template text NOT NULL,
    source text NOT NULL,
    precompiled_html text NOT NULL,
    precompiled_text text NOT NULL,
    allowed_variables text[] NOT NULL,
    compilation_errors text[] NOT NULL DEFAULT '{}',
    last_successful_compilation_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, name, version)
);

CREATE TABLE email_jobs (
    id uuid PRIMARY KEY,
    project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
    template_id uuid NOT NULL REFERENCES email_templates(id) ON DELETE RESTRICT,
    recipient text NOT NULL,
    variables jsonb NOT NULL,
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'leased', 'sent', 'failed', 'dead')),
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    available_at timestamptz NOT NULL DEFAULT now(),
    lease_expires_at timestamptz,
    provider_message_id text,
    last_error_code text,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX email_jobs_ready_idx ON email_jobs(available_at) WHERE status = 'pending';

CREATE TABLE project_migrations (
    project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
    migration_id text NOT NULL,
    name text NOT NULL,
    checksum bytea NOT NULL CHECK (octet_length(checksum) = 32),
    up_sql text NOT NULL,
    down_sql text NOT NULL,
    schema_version bigint NOT NULL CHECK (schema_version > 0),
    applied_by uuid NOT NULL,
    applied_at timestamptz NOT NULL DEFAULT now(),
    rolled_back_at timestamptz,
    PRIMARY KEY (project_id, migration_id),
    UNIQUE (project_id, schema_version)
);

CREATE TABLE usage_buckets (
    project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
    metric text NOT NULL,
    window_start timestamptz NOT NULL,
    window_seconds integer NOT NULL CHECK (window_seconds > 0),
    quantity bigint NOT NULL CHECK (quantity >= 0),
    PRIMARY KEY (project_id, metric, window_start)
);

CREATE TABLE rate_limit_state (
    bucket_key bytea PRIMARY KEY CHECK (octet_length(bucket_key) = 32),
    dimension text NOT NULL CHECK (dimension IN ('ip', 'project', 'user', 'api_key')),
    tokens double precision NOT NULL CHECK (tokens >= 0),
    last_refill_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL
);

CREATE TABLE audit_events (
    id uuid PRIMARY KEY,
    append_sequence bigint GENERATED ALWAYS AS IDENTITY UNIQUE,
    occurred_at timestamptz NOT NULL,
    organization_id uuid REFERENCES organizations(id) ON DELETE RESTRICT,
    project_id uuid REFERENCES projects(id) ON DELETE RESTRICT,
    request_id text NOT NULL,
    actor_kind text NOT NULL CHECK (actor_kind IN ('anonymous', 'user', 'api_key', 'operator', 'service')),
    actor_id uuid,
    action text NOT NULL,
    resource_kind text NOT NULL,
    resource_id uuid,
    outcome text NOT NULL CHECK (outcome IN ('success', 'denied', 'failure')),
    source_ip inet,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    prev_hash bytea,
    event_hash bytea NOT NULL CHECK (octet_length(event_hash) = 32),
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_events_project_time_idx ON audit_events(project_id, occurred_at DESC);
CREATE INDEX audit_events_actor_time_idx ON audit_events(actor_id, occurred_at DESC);

CREATE FUNCTION ffdb_deny_audit_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'audit events are append-only' USING ERRCODE = '42501';
END;
$$;
CREATE TRIGGER audit_events_no_update_or_delete
    BEFORE UPDATE OR DELETE ON audit_events
    FOR EACH ROW EXECUTE FUNCTION ffdb_deny_audit_mutation();

CREATE TABLE backups (
    id uuid PRIMARY KEY,
    project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
    database_id uuid NOT NULL REFERENCES project_databases(id) ON DELETE RESTRICT,
    provider_key text NOT NULL,
    sha256 bytea NOT NULL CHECK (octet_length(sha256) = 32),
    size_bytes bigint NOT NULL CHECK (size_bytes >= 0),
    encryption_key_version integer NOT NULL,
    state text NOT NULL CHECK (state IN ('creating', 'ready', 'restoring', 'failed', 'deleted')),
    created_by uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    verified_at timestamptz,
    CHECK (provider_key !~ '(^/|\.\.)')
);

CREATE TABLE idempotency_keys (
    project_id uuid NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
    operation text NOT NULL,
    key_hash bytea NOT NULL CHECK (octet_length(key_hash) = 32),
    request_hash bytea NOT NULL CHECK (octet_length(request_hash) = 32),
    response_status integer,
    response_body jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    PRIMARY KEY (project_id, operation, key_hash)
);
