import { mkdir, rename, unlink, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import type { SchemaSnapshot, TableDefinition } from "@ffdb/client";

interface ParsedColumn {
  readonly name: string;
  readonly type: string;
  readonly nullable: boolean;
}

const CONSTRAINT_WORDS = new Set([
  "AS",
  "CHECK",
  "COLLATE",
  "CONSTRAINT",
  "DEFAULT",
  "GENERATED",
  "NOT",
  "NULL",
  "PRIMARY",
  "REFERENCES",
  "UNIQUE",
]);

const TABLE_CONSTRAINTS = /^(?:CONSTRAINT\b|PRIMARY\s+KEY\b|UNIQUE\b|CHECK\b|FOREIGN\s+KEY\b)/i;

export function generateDatabaseTypes(schema: SchemaSnapshot): string {
  const tables = [...schema.tables].sort((left, right) => left.name < right.name ? -1 : left.name > right.name ? 1 : 0);
  const names = uniqueInterfaceNames(tables);
  const definitions = tables.map((table) => ({ table, columns: parseCreateTableColumns(table.sql) }));
  const usesBlob = definitions.some(({ columns }) => columns.some((column) => sqliteTypeToTypeScript(column.type) === "BlobValue"));
  const output = [
    "// AUTO-GENERATED BY @ffdb/cli. DO NOT EDIT.",
    `// FFDB schema version: ${schema.version}`,
    "",
  ];
  if (usesBlob) output.push('import type { BlobValue } from "@ffdb/client";', "");

  for (const { table, columns } of definitions) {
    const interfaceName = names.get(table.name);
    if (interfaceName === undefined) continue;
    if (columns.length === 0) {
      output.push(`export type ${interfaceName} = Readonly<Record<string, unknown>>;`, "");
      continue;
    }
    output.push(`export interface ${interfaceName} {`);
    for (const column of columns) {
      const nullableSuffix = column.nullable ? " | null" : "";
      output.push(`  readonly ${JSON.stringify(column.name)}: ${sqliteTypeToTypeScript(column.type)}${nullableSuffix};`);
    }
    output.push("}", "");
  }

  output.push("export interface Database {");
  for (const table of tables) {
    const interfaceName = names.get(table.name);
    if (interfaceName !== undefined) output.push(`  readonly ${JSON.stringify(table.name)}: ${interfaceName};`);
  }
  output.push("}", "");
  return `${output.join("\n")}\n`;
}

export async function writeDatabaseTypes(schema: SchemaSnapshot, outputPath: string): Promise<string> {
  const destination = resolve(outputPath);
  await mkdir(dirname(destination), { recursive: true });
  const temporary = `${destination}.${process.pid}.${Date.now()}.tmp`;
  try {
    await writeFile(temporary, generateDatabaseTypes(schema), { encoding: "utf8", flag: "wx" });
    await rename(temporary, destination);
  } catch (cause) {
    await unlink(temporary).catch(() => undefined);
    throw cause;
  }
  return destination;
}

function uniqueInterfaceNames(tables: readonly TableDefinition[]): ReadonlyMap<string, string> {
  const result = new Map<string, string>();
  const used = new Set<string>();
  for (const table of tables) {
    const stem = `Table${pascalCase(table.name) || "Anonymous"}`;
    let name = stem;
    let suffix = 2;
    while (used.has(name)) {
      name = `${stem}${suffix}`;
      suffix += 1;
    }
    used.add(name);
    result.set(table.name, name);
  }
  return result;
}

function pascalCase(value: string): string {
  return value
    .split(/[^A-Za-z0-9]+/u)
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join("")
    .replace(/^(?=\d)/u, "N");
}

function parseCreateTableColumns(sql: string): readonly ParsedColumn[] {
  const open = findFirstUnquoted(sql, "(");
  if (open < 0) return [];
  const close = findMatchingParenthesis(sql, open);
  if (close < 0) return [];
  const definitions = splitTopLevel(sql.slice(open + 1, close), ",");
  const columns: ParsedColumn[] = [];
  for (const definition of definitions) {
    const trimmed = definition.trim();
    if (trimmed.length === 0 || TABLE_CONSTRAINTS.test(trimmed)) continue;
    const identifier = readIdentifier(trimmed);
    if (identifier === null) continue;
    const remainder = trimmed.slice(identifier.end).trim();
    const type = readDeclaredType(remainder);
    const nullable = !/\bNOT\s+NULL\b/i.test(remainder) && !/\bPRIMARY\s+KEY\b/i.test(remainder);
    columns.push({ name: identifier.value, type, nullable });
  }
  return columns;
}

function sqliteTypeToTypeScript(type: string): string {
  const normalized = type.trim().toUpperCase();
  if (normalized.includes("INT")) return "number";
  if (/(?:CHAR|CLOB|TEXT)/u.test(normalized)) return "string";
  if (normalized.includes("BLOB")) return "BlobValue";
  if (/(?:REAL|FLOA|DOUB)/u.test(normalized)) return "number";
  if (/(?:DATE|TIME)/u.test(normalized)) return "number";
  return "unknown";
}

function readDeclaredType(value: string): string {
  const words = topLevelWords(value);
  const typeWords: string[] = [];
  for (const word of words) {
    if (CONSTRAINT_WORDS.has(word.value.toUpperCase())) break;
    typeWords.push(word.raw);
  }
  return typeWords.join(" ");
}

function topLevelWords(value: string): readonly { readonly raw: string; readonly value: string }[] {
  const words: { raw: string; value: string }[] = [];
  let start = -1;
  let depth = 0;
  let quote: string | null = null;
  for (let index = 0; index <= value.length; index += 1) {
    const character = value[index];
    if (index === value.length || (quote === null && depth === 0 && character !== undefined && /\s/u.test(character))) {
      if (start >= 0) {
        const raw = value.slice(start, index);
        words.push({ raw, value: raw.replace(/\(.*/su, "") });
        start = -1;
      }
      continue;
    }
    if (character === undefined) continue;
    if (start < 0) start = index;
    if (quote !== null) {
      if (character === quote && value[index + 1] === quote) index += 1;
      else if (character === quote || (quote === "]" && character === "]")) quote = null;
      continue;
    }
    if (character === "'" || character === '"' || character === "`") quote = character;
    else if (character === "[") quote = "]";
    else if (character === "(") depth += 1;
    else if (character === ")" && depth > 0) depth -= 1;
  }
  return words;
}

function readIdentifier(value: string): { readonly value: string; readonly end: number } | null {
  const first = value[0];
  if (first === undefined) return null;
  if (first === '"' || first === "`") {
    let result = "";
    for (let index = 1; index < value.length; index += 1) {
      const character = value[index];
      if (character === first && value[index + 1] === first) {
        result += first;
        index += 1;
      } else if (character === first) return { value: result, end: index + 1 };
      else result += character;
    }
    return null;
  }
  if (first === "[") {
    const end = value.indexOf("]", 1);
    return end < 0 ? null : { value: value.slice(1, end), end: end + 1 };
  }
  const match = /^[^\s,()]+/u.exec(value);
  return match?.[0] === undefined ? null : { value: match[0], end: match[0].length };
}

function splitTopLevel(value: string, separator: string): readonly string[] {
  const parts: string[] = [];
  let start = 0;
  let depth = 0;
  let quote: string | null = null;
  for (let index = 0; index < value.length; index += 1) {
    const character = value[index];
    if (quote !== null) {
      if (character === quote && value[index + 1] === quote) index += 1;
      else if (character === quote || (quote === "]" && character === "]")) quote = null;
      continue;
    }
    if (character === "'" || character === '"' || character === "`") quote = character;
    else if (character === "[") quote = "]";
    else if (character === "(") depth += 1;
    else if (character === ")" && depth > 0) depth -= 1;
    else if (character === separator && depth === 0) {
      parts.push(value.slice(start, index));
      start = index + 1;
    }
  }
  parts.push(value.slice(start));
  return parts;
}

function findFirstUnquoted(value: string, target: string): number {
  let quote: string | null = null;
  for (let index = 0; index < value.length; index += 1) {
    const character = value[index];
    if (quote !== null) {
      if (character === quote && value[index + 1] === quote) index += 1;
      else if (character === quote || (quote === "]" && character === "]")) quote = null;
    } else if (character === "'" || character === '"' || character === "`") quote = character;
    else if (character === "[") quote = "]";
    else if (character === target) return index;
  }
  return -1;
}

function findMatchingParenthesis(value: string, open: number): number {
  let depth = 0;
  let quote: string | null = null;
  for (let index = open; index < value.length; index += 1) {
    const character = value[index];
    if (quote !== null) {
      if (character === quote && value[index + 1] === quote) index += 1;
      else if (character === quote || (quote === "]" && character === "]")) quote = null;
      continue;
    }
    if (character === "'" || character === '"' || character === "`") quote = character;
    else if (character === "[") quote = "]";
    else if (character === "(") depth += 1;
    else if (character === ")") {
      depth -= 1;
      if (depth === 0) return index;
    }
  }
  return -1;
}
